volumes:
  stock_exchange_kts:

services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: stock_exchange
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
