"""Game_id field added to UserStock

Revision ID: 2e15232896ca
Revises: 014664121a5b
Create Date: 2024-05-19 11:52:50.115286

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e15232896ca'
down_revision: Union[str, None] = '014664121a5b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_stock', sa.Column('game_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'user_stock', 'game', ['game_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_stock', type_='foreignkey')
    op.drop_column('user_stock', 'game_id')
    # ### end Alembic commands ###
