"""Updated models fields types

Revision ID: b5e3a398d283
Revises: 4581c63f59f2
Create Date: 2024-05-13 22:02:53.535697

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b5e3a398d283'
down_revision: Union[str, None] = '4581c63f59f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game', sa.Column('chat_id', sa.String(), nullable=False))
    op.create_unique_constraint('user_game_unique_constraint', 'game_user', ['user_id', 'game_id'])
    op.add_column('user', sa.Column('telegram_id', sa.BigInteger(), nullable=False))
    op.alter_column('user', 'first_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('user', 'last_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('user', 'username',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint('user_username_key', 'user', type_='unique')
    op.create_unique_constraint('telegram_id_unique_constraint', 'user', ['telegram_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('telegram_id_unique_constraint', 'user', type_='unique')
    op.create_unique_constraint('user_username_key', 'user', ['username'])
    op.alter_column('user', 'username',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('user', 'last_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('user', 'first_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('user', 'telegram_id')
    op.drop_constraint('user_game_unique_constraint', 'game_user', type_='unique')
    op.drop_column('game', 'chat_id')
    # ### end Alembic commands ###
