"""Added total_quantity to UserStock

Revision ID: f21a39133f10
Revises: bb7f40a62c91
Create Date: 2024-05-17 21:42:18.630833

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f21a39133f10'
down_revision: Union[str, None] = 'bb7f40a62c91'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('stock_title_unique_constraint', 'stock', ['title'])
    op.add_column('user_stock', sa.Column('total_quantity', sa.Integer(), nullable=False))
    op.drop_column('user_stock', 'sell_quantity')
    op.drop_column('user_stock', 'buy_quantity')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_stock', sa.Column('buy_quantity', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('user_stock', sa.Column('sell_quantity', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('user_stock', 'total_quantity')
    op.drop_constraint('stock_title_unique_constraint', 'stock', type_='unique')
    # ### end Alembic commands ###
